server.port=8080
shareit-server.url=${SHAREIT_SERVER_URL:http://shareit-server:9090}
server.address=0.0.0.0

# Expose health endpoint for CI wait-for-it check
management.endpoints.web.exposure.include=health
management.endpoint.health.enabled=true

